### ISSUE TITLE
Can't Delete Last Row of Repeater

### ISSUE THREAD

**Issue by jwood01** [Hube2/acf-user-role-field-setting#11]
When this plugin is active, the user is unable to delete the last row of a repeater field.

Lastest version of PRO ACF installed.

Yes, checked with vanilla setup … no other plugins except ACF PRO and Twenty Seventeen theme. Same result.

Thank you for your attention.

**Comment by jwood01** [comment]
[acf-export-2017-09-07.txt](https://github.com/Hube2/acf-user-role-field-setting/files/1286263/acf-export-2017-09-07.txt)

This is the field


                "key": "field_58dd1b4f4b8be",
                "label": "Passenger Detail",
                "name": "leg_passenger_detail",
                "type": "repeater",

Attached is the entire associated export.

**Comment by Hube2** [comment]
Just tried opening that file and there's nothing in it. try saving it as a .json file and then .zip it before you try to attach it here.  I can't really tell anything from the small snippet of the field that you attached.

**Comment by davelavoie** [comment]
@jwood01 see #12 for a fix!
