### ISSUE TITLE
Repeater rows not deleting: the preg_match rule should match the last key of the field name, not the first one.

### ISSUE THREAD

**Issue by davelavoie** [Hube2/acf-user-role-field-setting#12]
On the following line:
https://github.com/Hube2/acf-user-role-field-setting/blob/d36e8a8aaf8f1731b3cb3cd6f3484e893caec994/acf-user-role-field-setting.php#L80

Instead of using the `/(\[[^\]]+\])/` rule, it should instead use the `/(\[[^\]]+\])$/` rule (see the $ added at the end of the rule), since we want to catch the last part of the key. 

This is why it's not possible to delete a repeater row when a condition based on the user role is set, but not met, for any field inside the repeater. Actually, the issue is probably happening with any kind of fields that can be nested, as I was able to trigger it with repeater fields, group fields, flexible content fields...

Currently, if a field in a repeater or group has the following name for example: `acf[field_5a8c41e66619b][field_5b15bcb222e40]` . With the current rule, it'll use `[field_5a8c41e66619b]` (which is the key for the repeater/group field) when creating the hidden acf_deleted input. Which means the whole repeater/group will be fetched when saving the post, and any deleted field in the repeater/group will be overridden with the value we've just deleted.

However, if we use the rule I'm suggesting, the match will instead be `[field_5b15bcb222e40]`, which is the right key to use when calling the get_removed method.

Try it:

1. With the plugin activated, create a group field. 
2. Inside that group, create a repeater. 
3. Then in the repeater, add a file field. 
4. Then, add a second field to the group (or the repeater), and apply a user role condition.  Choose a condition that you won't be able to met (ex: you must be editor but you're author), or else the issue won't happen.
5. Now, go edit the post to which the fields you've just created are mapped. Create 3 or 4 rows and add files to each rows. Then, save.
6. Once the post has been saved, try to delete one of the row, and then save again. If a condition wasn't met for any field inside the group or repeater, then the row won't be deleted since its value will be overridden by the get_removed method.

Now, do the same with the rule I've suggested. It should work!

Hope it helps!

**Comment by Hube2** [comment]
Thanks for this, I will try to get this change in place later today.
