### ISSUE TITLE
Read only support

### ISSUE THREAD

**Issue by amjad** [Hube2/acf-user-role-field-setting#20]
Is it possible to extend this plugin to make certain fields Read Only for certain user roles? I only want Admin to edit them, but other roles should be at least be able to view them.

**Comment by zauker** [comment]
I made a 'dirty' fork of this plugin that draws the field as readonly instead as hidden.
https://github.com/zauker/acf-user-role-field-setting-advanced
If you want you can try it.

unluckily this plugin not have hook or filter that allow an override his behavior, so I made that fork.

**Comment by amjad** [comment]
Thanks, I’ll give it a try!

**Comment by zauker** [comment]
@amjad  let me know if it works fine ;)

**Comment by Hube2** [comment]
Unfortunately, setting the readonly attribute does not work on every type of field and the change does not account for repeater sub fields. The ability to make any type of field read only is more complex than making them un-editable and may not even be possible in some cases without showing completely different field types. Anything that uses Select2.
