### ISSUE TITLE
Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by adleviton** [Hube2/acf-user-role-field-setting#22]
I keep seeing the following error in my logs:

`Trying to access array offset on value of type bool`
`plugins/user-role-field-setting-for-acf/acf-user-role-field-setting.php:47`

**Comment by Hube2** [comment]
The only thing that could cause this is a filter that returns false on the hook acf/user_role_setting/exclude_field_types. If you are filtering this value then you need to return an empty array and not a boolean value.

**Comment by adleviton** [comment]
Thanks @Hube2. I found it, but still have a problem. It's on the `acf/prepare_field` hook, and I'm returning false [as advised by the documentation](https://www.advancedcustomfields.com/resources/acf-prepare_field/). Returning the `$field` stops the error I mentioned above, but renders the field (which I don't want). I also tried adjusting the hook priority, but no luck.

**Comment by adleviton** [comment]
Ok, I figured it out, and I'm working with a clone field:

- Clone source field =  All User Roles unchecked.
- Clone field = User Role checkboxes don't seem to make a difference here.
- acf/prepare_field = needs to return `$field`

Thanks again!

**Comment by misaki-web** [comment]
I get this warning too with v4.0.2. The only filter I have is an exact copy of the one described in the README file:

```php
add_filter('acf/user_role_setting/exclude_field_types', 'user_role_setting_excluded_field_types');
function user_role_setting_excluded_field_types($exclude) {
  /* 
    $exclude holds an array of field types to exclude from adding user role settings
    default value:
    $exclude = array('tab' => 'tab', 'clone' => 'clone');
  */
	
	// remove tab field from exclude
  if (isset($exclude['tab'])) {
    unset($exclude['tab']);
  }
	
	// add message field to exclude
	$exclude['message'] = 'message';
	
  return $exclude;
}
```

What's working to remove the warning is checking if `$field['type']` is isset here:

https://github.com/Hube2/acf-user-role-field-setting/blob/cf85dc4d06f5f15fac675d1fe0d7ad8d39b8d658/acf-user-role-field-setting.php#L45-L49

So, instead of:

```php
if (is_array($exclude) && in_array($field['type'], $exclude)) {
```

the new line is:

```php
if (isset($field['type']) && is_array($exclude) && in_array($field['type'], $exclude)) {
```
