### ISSUE TITLE
No effect in GUI following activation

### ISSUE THREAD

**Issue by cheekygit** [Hube2/acf-user-role-field-setting#4]
Version 2.1.1 of your plugin, v5.5.3 of ACF
Your nag box appears, but I cannot find the new field setting user role for all field types.

**Comment by Hube2** [comment]
thanks for the bug report, now to figure out why it stopped working.

**Comment by Hube2** [comment]
Organization of array returned by acf_get_field_types() altered in ACF 5.5... I think. Need to add logic for before/after 5.5 and add render field action differently depending on version.

**Comment by Hube2** [comment]
The new version should correct the problem for ACF 5.5. Please test and let me know.

**Comment by cheekygit** [comment]
I still cannot see a GUI for setting allowed user roles on field types... There should be an additional dropdown somewhere?

**Comment by Hube2** [comment]
there should be checkboxes right after the required setting. I'm seeing them now.
![image](https://cloud.githubusercontent.com/assets/6631975/21550982/034a694e-cdcc-11e6-9f7e-0a626dffc269.png). 

There is logic to test of your ACF version is less than or greater than 5.5 and the new setting is added based on the result. The only reason you would not see the setting now is if your db was not updated with the new ACF version for some reason.

**Comment by cheekygit** [comment]
I had installed v2.1.1 manually, then updated to v2.1.2 using GitHub auto-updater as recommended by you. This update seems to have failed silently showing the new version in plugins overview but not actually updating the plugin as when I re-installed v2.1.2 manually, the section from your screenshot appears for me too. I hope future updates using GitHub auto-updater will work. Ok, now I can actually test your plugin. One suggestion already: add a checkbox for super admins.

**Comment by Hube2** [comment]
There is a checkbox for super admin when it is installed on multisite. It does not appear if it's not a multisite install.

Sometimes the github updated fails and I don't know what the cause of it is

**Comment by cheekygit** [comment]
Super admin box confirmed, thanks. So good...
