### ISSUE TITLE
Field is admin only, value not output in theme?

### ISSUE THREAD

**Issue by matedw** [Hube2/acf-user-role-field-setting#6]
I'm not sure if I'm not reading the capability of the plugin correctly so this may not actually be an issue at all...

I have set a field within a group to be visible to Administrators only. This is working well.

However, I would like the value to be output via the theme regardless of user role. Does this plugin allow this?

**Comment by Hube2** [comment]
No. This plugin does not make make a field visible but not editable. For something like this you should look into using a standard acf/load_field filter and making the field read only. There isn't anything in ACF that will let you show a field as anything other than a field, for example, displaying the value of a field as just text.

**Comment by Hube2** [comment]
And I could have completely misunderstood the question. This plugin only effects the editing of values where they can be edited. It does not interfere with any other functions of ACF and you can use `the_field()`, `get_field()` and other ACF functions normally.
