### ISSUE TITLE
convert fields to messages?

### ISSUE THREAD

**Issue by Hube2** [Hube2/acf-user-role-field-setting#8]
Something to think about. Setting to say to convert field value to a message field instead of removing it.
https://wordpress.org/support/topic/allow-to-view-but-can-not-edit/

**Comment by andrija-naglic** [comment]
I just came across this plugin and didn't yet devote too much time investigating it's code, but - you already know which fields the user is not supposed to have access to.

If you can display such fields with a CSS class that would give them some opacity and pointer-events: none, then you could "disable" the fields, at least in the eyes of the user.

The actual disabling would happen in the action just before the post save, which I guess you are already doing (with 'acf/user_role_setting/exclude_field_types' or something), so even if the user alters HTML/CSS, the fields would never actually be saved, thus we could call them read only fields.

Does this make sense?

**Comment by Hube2** [comment]
I never though of it this way. What happens on submit is that this plugin filters $_POST removing any values that the user should not be able to edit so that ACF does not process them. My main goal here was security, not necessarily making them read only.

I suppose that the fields could still be displayed and made read only since they cannot be submitted, but that opens a whole new kettle of fish. Many of the field types in ACF I wouldn't begin to know how to set as read only. For example, I know that a read only option is not yet available for Select2 fields. Radio an check boxes present other problems. There isn't anything in the plugin that deals with specific field types, all field types are treated the same.

I could add a class to the wrapper of the field, for example "not-editable" or something. But to display the field and not go to the trouble of making it read only in some way would only be inviting complaints about being able to alter values and when am I going to make them actually "read only"

Showing fields and not letting them be submitted would be simple, but it would not be a very "clean" solution.

I'll have to give this some thought.

I'm going to tell you that I like to keep my projects in an extremely tight scope. The main reason for this is that if they morph too far out of that scope I simply won't have time to maintain it. Dealing with each type of field the way it needs to be dealt with would vastly increase the amount of work I'd need to do. This is one of the main reasons that I haven't put time into making fields into message fields, because many fields will require special treatment to convert the values to messages.

'acf/user_role_setting/exclude_field_types' is actually just a filter that lets you remove the setting and checking for certain field types as a way of removing clutter from the ACF field group editor admin and to prevent checking of certain types of fields in order to speed up the processing for those that desire to do so.
